variables:
  CORENEURON_BRANCH:
    description: Branch of CoreNEURON to build (CORENEURON_COMMIT and CORENEURON_TAG also possible)
    value: master
  NEURON_BRANCH:
    description: Branch of NEURON to build (NEURON_COMMIT and NEURON_TAG also possible)
    value: master
  NMODL_BRANCH:
    description: Branch of NMODL to build (NMODL_COMMIT and NMODL_TAG also possible)
    value: master
  SPACK_BRANCH:
    description: Branch of BlueBrain Spack to use for the CI pipeline.
    value: develop
  SPACK_DEPLOYMENT_SUFFIX:
    description: Extra path component used when finding deployed software. Set to something like `pulls/1497` use software built for https://github.com/BlueBrain/spack/pull/1497. You probably want to set SPACK_BRANCH to the branch used in the relevant PR if you set this.
    value: ''

include:
  - project: hpc/gitlab-pipelines
    file: spack-build-components.gitlab-ci.yml

spack_setup:
  extends: .spack_setup_ccache

venv:
  tags: [bb5_map]
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - module load unstable git python-dev
    - python -m venv venv
    - source venv/bin/activate
    - python setup.py install
    - echo "CVF_VENV_ROOT=${PWD}" > venv_location.env
    - CVF_MODELS_ROOT=${PWD}/clone
    - echo "CVF_MODELS_ROOT=${CVF_MODELS_ROOT}" >> venv_location.env
    # In case we need to retry the venv/ job on GitLab
    - rm -rf "${CVF_MODELS_ROOT}"
    # This clones all of the BBP models and common MOD files in one go.
    - git clone --recursive --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@bbpgitlab.epfl.ch/hpc/sim/neurodamus-models.git "${CVF_MODELS_ROOT}"
  artifacts:
    when: always
    paths: [venv_location.env]
    reports:
      dotenv: venv_location.env

nmodl:
  extends: .spack_build
  variables:
    SPACK_PACKAGE: nmodl
    SPACK_PACKAGE_SPEC: +python

neuron:
  extends: .spack_build
  variables:
    SPACK_PACKAGE: neuron
    SPACK_PACKAGE_COMPILER: intel
    SPACK_PACKAGE_SPEC: build_type=Debug

coreneuron:
  extends: .spack_build
  variables:
    SPACK_PACKAGE: coreneuron
    SPACK_PACKAGE_COMPILER: intel
    SPACK_PACKAGE_SPEC: ~report build_type=Debug

coreneuron_nmodl:
  extends: .spack_build
  variables:
    SPACK_PACKAGE: coreneuron
    SPACK_PACKAGE_COMPILER: intel
    SPACK_PACKAGE_SPEC: +nmodl~report build_type=Debug
  needs: [nmodl]
  
coreneuron_nmodl_ispc:
  extends: .spack_build
  variables:
    SPACK_PACKAGE: coreneuron
    SPACK_PACKAGE_COMPILER: intel
    SPACK_PACKAGE_SPEC: +nmodl+ispc~report build_type=Debug
  needs: [nmodl]

test:
  extends: .spack_test
  script:
    # Change to the working directory of the `venv` job
    - cd ${CVF_VENV_ROOT}
    - module load unstable git python-dev intel-oneapi-compilers
    - spack load nmodl@develop+python neuron@develop%intel
    - source venv/bin/activate
    - cvf_stdrun -d test/${MOD_FILES_PROJECT} ${CVF_MODELS_ROOT}/${MOD_FILES_PROJECT}/${MOD_FOLDER}
  parallel:
    matrix:
      - MOD_FILES_PROJECT: hippocampus
        MOD_FOLDER: mod
      - MOD_FILES_PROJECT: mousify
        MOD_FOLDER: mod
      - MOD_FILES_PROJECT: neocortex
        MOD_FOLDER: mod/v5
      - MOD_FILES_PROJECT: thalamus
        MOD_FOLDER: mod
  needs:
    - venv
    - neuron
    - coreneuron
    - coreneuron_nmodl
    - coreneuron_nmodl_ispc
