modignore: # These are the mod dirs that are ignored for all the runs. You can also remove mod files from compilation or testing in each run setup
    nocompile: # Not compiled
        netstim_inhpoisson: artificial cell not supported
        VecStim: artificial cell not supported
        GluSynapse: does not compile correctly
        StochKv: setRNG for suffix not supported
    notest: # Not tested
        TTXDynamicsSwitch: service mechanism used in conjunction with others. Testing it alone is not meaningful
        cvf_svclmp: reserved for cvf

neuron: #Base run. This name determines:
        # - how the simulation is run (neuron/coreneuron)
        # - on what we compare results.
        #
        # Do not change it unless you know what you are doing.
    compile_commands:
        - $(spack location -i neuron@develop)/bin/nrnivmodl mod/

coreneuron-nmodl:
    compile_commands:
        - $(spack location -i neuron@develop)/bin/nrnivmodl mod/
        - $(spack location -i neuron@develop)/bin/nrnivmodl-core -a "host --c passes --inline codegen --force" mod/
    modignore:
        nocompile:
            cagk: Small discrepancy with neuron reported in nmodl issue \#432. Reenable this once it is solved
            NaV: sparse solver not supported by nmodl without sympy
            TC_Ih_CaMod: sparse solver not supported by nmodl without sympy
    rtol: 0.0
    atol: 0.0
