
pipeline {
    agent {
        label 'bb5'
    }
    parameters {
        string(name: 'SPACK_BRANCH', defaultValue: '',
               description: 'Which branch of spack to use.')
        string(name: 'NEURON_BRANCH', defaultValue: '',
               description: 'Which branch of neuron to use. For master branch (neuron@develop) leave this parameter blank.')
        string(name: 'CORENEURON_BRANCH', defaultValue: '',
               description: 'Which branch of coreneuron to use. For master branch (coreneuron@develop) leave this parameter blank.')
        string(name: 'NMODL_BRANCH', defaultValue: '',
               description: 'Which branch of nmodl to use. For master branch (nmodl@master) leave this parameter blank.')
    }

    environment {
        HOME = "${WORKSPACE}"
        JENKINS_DIR = "${WORKSPACE}/.jenkins"
    }

    stages {

        stage('Spack Setup'){
            steps {
                sh 'source $JENKINS_DIR/spack_setup.sh'
            }
        }

        stage('Spack Install'){
            steps {
                sh 'source $JENKINS_DIR/spack_install.sh'
            }
        }

        stage('Run Tests'){
            steps{
                sh 'source $JENKINS_DIR/run_tests.sh'
            }
        }
    }
}