
wiggle:
  global:
    data:
      v_init: -80.0
  sections:
    soma:
      data:
        L: 20.0
        Ra: 150.0
        diam: 20.0
        g_pas: 3.334e-05
      inputs:
        cai:
          t_steps:
          - 100.0
          - 800.0
          - 400.0
          - 400.0
          - 400.0
          - 200.0
          - 400.0
          - 100.0
          - 100.0
          y_steps:
          - 2.4e-05
          - 1.0e-04
          - 2.4e-05
          - 2.0e-04
          - 2.4e-05
          - 4.0e-04
          - 2.4e-05
          - 3.0e-05
          - 2.4e-05
      mechanisms:
        kca:
          type: SUFFIX
      record_traces:
        - ik


