channel:
  L: 20.0
  Ra: 150.0
  diam: 20.0
  g_pas: 3.334e-05
  NONSPECIFIC_CURRENT: 0.0
  USEION:
    READ: -88.0
  section: soma
  SUFFIX: REPLACEME
  type: outward
  v_init: -80.0
stimulus:
  Ramp:
    clamp_mode: voltage
    thold1: 100.0
    thold2: 800.0
    thold3: 400.0
    thold4: 400.0
    thold5: 400.0
    thold6: 200.0
    thold7: 400.0
    thold8: 100.0
    thold9: 100.0
    tstop: 2900.0
    type: ramp
    vhold: -80.0
    vmax: 70.0


