channel:
  L: 20.0
  Ra: 150.0
  current: TODO
  diam: 20.0
  g_pas: 3.334e-05
  revName: TODO
  revValue: -88.0
  section: soma
  suffix: TODO
  type: outward
  v_init: -80.0
stimulus:
  Activation:
    clamp_mode: voltage
    thold1: 100.0
    thold2: 500.0
    thold3: 100.0
    tstop: 700.0
    type: step1
    vhold1: -80.0
    vhold2:
    - -90.0
    - 10.0
    - 50.0
    vhold3: -80.0
  Deactivation:
    clamp_mode: voltage
    thold1: 100.0
    thold2: 300.0
    thold3: 200.0
    thold4: 100.0
    tstop: 700.0
    type: step2
    vhold1: -80.0
    vhold2: 70.0
    vhold3:
    - -100.0
    - 10.0
    - 40.0
    vhold4: -80.0
  Inactivation:
    clamp_mode: voltage
    thold1: 100.0
    thold2: 1500.0
    thold3: 50.0
    thold4: 100.0
    tstop: 1750.0
    type: step2
    vhold1: -80.0
    vhold2:
    - -40.0
    - 10.0
    - 70.0
    vhold3: 30.0
    vhold4: -80.0
  Ramp:
    clamp_mode: voltage
    thold1: 100.0
    thold2: 800.0
    thold3: 400.0
    thold4: 400.0
    thold5: 400.0
    thold6: 200.0
    thold7: 400.0
    thold8: 100.0
    thold9: 100.0
    tstop: 2900.0
    type: ramp
    vhold: -80.0
    vmax: 70.0
