channel:
  L: 20.0
  Ra: 150.0
  diam: 20.0
  g_pas: 3.334e-05
  NONSPECIFIC_CURRENT: 0.0
  USEION:
    READ: -88.0
  section: soma
  type: outward
  v_init: -80.0
  netcon:
    weight: 1.3
    threshold: 11
    delay: 53
  rng:
    - 3
    - 7
    - 13
stimulus:
  wiggle:
    clamp_mode: voltage
    t_steps:
    - 100.0
    - 800.0
    - 400.0
    - 400.0
    - 400.0
    - 200.0
    - 400.0
    - 100.0
    - 100.0
    tstop: 2900.0
    type: ramp
    v_steps:
    - -20.0
    - 20.0
    - -20.0
    - 20.0
    - -20.0
    - 20.0
    - -20.0
    - 20.0
    - -20.0
  Ramp:
    clamp_mode: voltage
    t_steps:
    - 100.0
    - 800.0
    - 400.0
    - 400.0
    - 400.0
    - 200.0
    - 400.0
    - 100.0
    - 100.0
    tstop: 2900.0
    type: ramp
    v_steps:
    - -80.0
    - -61.25
    - -42.5
    - -23.75
    - -5.0
    - 13.75
    - 32.5
    - 51.25
    - 70.0
  Activation:
    clamp_mode: voltage
    t_steps:
    - 100.0
    - 500.0
    - 100.0
    tstop: 700.0
    type: step1
    v_steps:
    - -80.0
    - - -90.0
      - 10.0
      - 50.0
    - -80.0
  Deactivation:
    clamp_mode: voltage
    t_steps:
    - 100.0
    - 300.0
    - 200.0
    - 100.0
    tstop: 700.0
    type: step2
    v_steps:
    - -80.0
    - 70.0
    - - -100.0
      - 10.0
      - 40.0
    - -80.0
  Inactivation:
    clamp_mode: voltage
    t_steps:
    - 100.0
    - 1500.0
    - 50.0
    - 100.0
    tstop: 1750.0
    type: step2
    v_steps:
    - -80.0
    - - -40.0
      - 10.0
      - 70.0
    - 30.0
    - -80.0

