wiggle:
  global:
    data:
      v_init: -30.0
  sections:
    soma:
      data:
        L: 20.0
        Ra: 150.0
        diam: 20.0
        g_pas: 3.334e-05
      inputs:
        ica:
          t_steps:
          - 100.0
          - 800.0
          - 400.0
          - 400.0
          - 400.0
          - 200.0
          - 400.0
          - 100.0
          - 100.0
          y_steps:
          - -20.0
          - 20.0
          - -20.0
          - 20.0
          - -20.0
          - 20.0
          - -20.0
          - 20.0
          - -20.0
      mechanisms:
        CaDynamics_DC0:
          data:
            ica: 13
          type: SUFFIX
      record_traces:
      - cai
